In [1]:
import numpy as np
import pandas as pd
import cv2
from sklearn.metrics import accuracy_score,confusion_matrix
import matplotlib.pyplot as plt
import glob

In [2]:
glioma=[]
meningioma=[]
notumor=[]
pituitary=[]
path1='./Training/glioma/*.jpg'
path2='./Training/meningioma/*.jpg'
path3='./Training/notumor/*.jpg'
path4='./Training/pituitary/*.jpg'
for i in glob.iglob(path1):
    img=cv2.imread(i)
    img=cv2.resize(img,(128,128))
    glioma.append(img)
for j in glob.iglob(path2):
    img=cv2.imread(j)
    img=cv2.resize(img,(128,128))
    meningioma.append(img)
for k in glob.iglob(path3):
    img=cv2.imread(k)
    img=cv2.resize(img,(128,128))
    notumor.append(img)
for l in glob.iglob(path4):
    img=cv2.imread(l)
    img=cv2.resize(img,(128,128))
    pituitary.append(img)

In [3]:
glioma_t=[]
meningioma_t=[]
notumor_t=[]
pituitary_t=[]
path1='./Testing/glioma/*.jpg'
path2='./Testing/meningioma/*.jpg'
path3='./Testing/notumor/*.jpg'
path4='./Testing/pituitary/*.jpg'
for i in glob.iglob(path1):
    img=cv2.imread(i)
    img=cv2.resize(img,(128,128))
    glioma_t.append(img)
for j in glob.iglob(path2):
    img=cv2.imread(j)
    img=cv2.resize(img,(128,128))
    meningioma_t.append(img)
for k in glob.iglob(path3):
    img=cv2.imread(k)
    img=cv2.resize(img,(128,128))
    notumor_t.append(img)
for l in glob.iglob(path4):
    img=cv2.imread(l)
    img=cv2.resize(img,(128,128))
    pituitary_t.append(img)

In [4]:
data=[]
for i in glioma:
    data.append(i)
for i in meningioma:
    data.append(i)
for i in notumor:
    data.append(i)
for i in pituitary:
    data.append(i)
print(len(data))
labels=[]
for i in range(len(glioma)):
    labels.append(0)
for i in range(len(meningioma)):
    labels.append(1)
for i in range(len(notumor)):
    labels.append(2)
for i in range(len(pituitary)):
    labels.append(3)
print(len(labels))

5712
5712


In [5]:
data_t=[]
for i in glioma_t:
    data_t.append(i)
for i in meningioma_t:
    data_t.append(i)
for i in notumor_t:
    data_t.append(i)
for i in pituitary_t:
    data_t.append(i)
print(len(data_t))
labels_t=[]
for i in range(len(glioma_t)):
    labels_t.append(0)
for i in range(len(meningioma_t)):
    labels_t.append(1)
for i in range(len(notumor_t)):
    labels_t.append(2)
for i in range(len(pituitary_t)):
    labels_t.append(3)
print(len(labels_t))

1311
1311


In [6]:
X=np.asarray(data)
X = X.reshape(X.shape[0], -1)
print("Reshaped shape:", X.shape)
Y=np.asarray(labels)
Y = Y.ravel()
print("New shape:", Y.shape)

Reshaped shape: (5712, 49152)
New shape: (5712,)


In [7]:
X_t=np.asarray(data_t)
X_t = X_t.reshape(X_t.shape[0], -1)
print("Reshaped shape:", X_t.shape)
Y_t=np.asarray(labels_t)
Y_t= Y_t.ravel()
print("New shape:", Y_t.shape)

Reshaped shape: (1311, 49152)
New shape: (1311,)


In [8]:
x_train,x_test,y_train,y_test=X,X_t,Y,Y_t

In [9]:
from sklearn.svm import SVC
model = SVC(kernel='linear')
model.fit(x_train, y_train)

SVC(kernel='linear')

In [10]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 3, 3, 3])

In [11]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9107551487414187

In [12]:
confusion_matrix(y_test,y_pred)

array([[245,  51,   1,   3],
       [ 40, 254,   7,   5],
       [  0,   1, 403,   1],
       [  1,   6,   1, 292]], dtype=int64)

In [13]:
data_n=data+data_t
print(len(data_n))
labels_n=labels+labels_t
print(len(labels_n))

7023
7023


In [14]:
X_n=np.asarray(data_n)
X_n = X_n.reshape(X_n.shape[0], -1)
print("Reshaped shape:", X_n.shape)
Y_n=np.asarray(labels_n)
Y_n= Y_n.ravel()
print("New shape:", Y_n.shape)

Reshaped shape: (7023, 49152)
New shape: (7023,)


In [15]:
from sklearn.model_selection import cross_val_score
cross_val=cross_val_score(model,X_n,Y_n, cv=5,n_jobs=-1,verbose=1)
cross_val

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 13.3min finished


array([0.73380783, 0.8747331 , 0.84768683, 0.82336182, 0.88532764])

In [16]:
print(cross_val.mean())

0.8329834433393153


In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       300
           1       0.81      0.83      0.82       306
           2       0.98      1.00      0.99       405
           3       0.97      0.97      0.97       300

    accuracy                           0.91      1311
   macro avg       0.90      0.90      0.90      1311
weighted avg       0.91      0.91      0.91      1311



In [ ]:
from sklearn.model_selection import RandomizedSearchCV
classifier=SVC(kernel='linear')
scoring=['f1','precision','recall']
parameters=[{'gamma':[0.1,0.01,0.001],'C':[0.1,1,10,100]}]
randomized_search=RandomizedSearchCV(classifier,parameters,n_jobs=-1,refit=True,return_train_score=True,scoring=['f1','precision','recall'])
randomized_search.fit(x_train,y_train)

In [ ]:
best_estimator=grid_search.best_estimator_
best_estimator

In [ ]:
y_prediction=best_estimator.predict(x_test)
y_prediction

In [ ]:
accuracy=accuracy_score(y_test,y_prediction)
accuracy

In [ ]:
print(classification_report(y_test,y_pred))