In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

print("Path to dataset files:", path)

/home/codespace/.python/current/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 149M/149M [00:10<00:00, 14.5MB/s] 

Extracting files...


Path to dataset files: /home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1


In [2]:
import numpy as np
import pandas as pd
import cv2
from sklearn.metrics import accuracy_score,confusion_matrix
import matplotlib.pyplot as plt
import glob

In [3]:
glioma=[]
meningioma=[]
notumor=[]
pituitary=[]
path1='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Training/glioma/*.jpg'
path2='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Training/meningioma/*.jpg'
path3='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Training/notumor/*.jpg'
path4='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Training/pituitary/*.jpg'
for i in glob.iglob(path1):
    img=cv2.imread(i)
    img=cv2.resize(img,(128,128))
    glioma.append(img)
for j in glob.iglob(path2):
    img=cv2.imread(j)
    img=cv2.resize(img,(128,128))
    meningioma.append(img)
for k in glob.iglob(path3):
    img=cv2.imread(k)
    img=cv2.resize(img,(128,128))
    notumor.append(img)
for l in glob.iglob(path4):
    img=cv2.imread(l)
    img=cv2.resize(img,(128,128))
    pituitary.append(img)

In [4]:
glioma_t=[]
meningioma_t=[]
notumor_t=[]
pituitary_t=[]
path1='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Testing/glioma/*.jpg'
path2='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Testing/meningioma/*.jpg'
path3='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Testing/notumor/*.jpg'
path4='/home/codespace/.cache/kagglehub/datasets/masoudnickparvar/brain-tumor-mri-dataset/versions/1/Testing/pituitary/*.jpg'
for i in glob.iglob(path1):
    img=cv2.imread(i)
    img=cv2.resize(img,(128,128))
    glioma_t.append(img)
for j in glob.iglob(path2):
    img=cv2.imread(j)
    img=cv2.resize(img,(128,128))
    meningioma_t.append(img)
for k in glob.iglob(path3):
    img=cv2.imread(k)
    img=cv2.resize(img,(128,128))
    notumor_t.append(img)
for l in glob.iglob(path4):
    img=cv2.imread(l)
    img=cv2.resize(img,(128,128))
    pituitary_t.append(img)

In [5]:
data=[]
for i in glioma:
    data.append(i)
for i in meningioma:
    data.append(i)
for i in notumor:
    data.append(i)
for i in pituitary:
    data.append(i)
print(len(data))
labels=[]
for i in range(len(glioma)):
    labels.append(0)
for i in range(len(meningioma)):
    labels.append(1)
for i in range(len(notumor)):
    labels.append(2)
for i in range(len(pituitary)):
    labels.append(3)
print(len(labels))

5712
5712


In [6]:
data_t=[]
for i in glioma_t:
    data_t.append(i)
for i in meningioma_t:
    data_t.append(i)
for i in notumor_t:
    data_t.append(i)
for i in pituitary_t:
    data_t.append(i)
print(len(data_t))
labels_t=[]
for i in range(len(glioma_t)):
    labels_t.append(0)
for i in range(len(meningioma_t)):
    labels_t.append(1)
for i in range(len(notumor_t)):
    labels_t.append(2)
for i in range(len(pituitary_t)):
    labels_t.append(3)
print(len(labels_t))

1311
1311


In [7]:
X=np.asarray(data)
X = X.reshape(X.shape[0], -1)
print("Reshaped shape:", X.shape)
Y=np.asarray(labels)
Y = Y.ravel()
print("New shape:", Y.shape)

Reshaped shape: (5712, 49152)
New shape: (5712,)


In [8]:
X_t=np.asarray(data_t)
X_t = X_t.reshape(X_t.shape[0], -1)
print("Reshaped shape:", X_t.shape)
Y_t=np.asarray(labels_t)
Y_t= Y_t.ravel()
print("New shape:", Y_t.shape)

Reshaped shape: (1311, 49152)
New shape: (1311,)


In [9]:
x_train,x_test,y_train,y_test=X,X_t,Y,Y_t

In [10]:
from sklearn.svm import SVC
model = SVC(kernel='poly')
model.fit(x_train, y_train)

SVC(kernel='poly')

In [11]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, ..., 3, 3, 3], shape=(1311,))

In [12]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.9183829138062548

In [13]:
confusion_matrix(y_test,y_pred)

array([[268,  27,   1,   4],
       [ 37, 254,   5,  10],
       [  9,   2, 393,   1],
       [  8,   3,   0, 289]])

In [14]:
data_n=data+data_t
print(len(data_n))
labels_n=labels+labels_t
print(len(labels_n))

7023
7023


In [15]:
X_n=np.asarray(data_n)
X_n = X_n.reshape(X_n.shape[0], -1)
print("Reshaped shape:", X_n.shape)
Y_n=np.asarray(labels_n)
Y_n= Y_n.ravel()
print("New shape:", Y_n.shape)

Reshaped shape: (7023, 49152)
New shape: (7023,)


In [17]:
from sklearn.model_selection import cross_val_score
cross_val=cross_val_score(model,X_n,Y_n, cv=5,verbose=1)
cross_val

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed: 17.3min finished


array([0.89323843, 0.91459075, 0.89893238, 0.91310541, 0.92165242])

In [18]:
print(cross_val.mean())

0.9083038801188268


In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86       300
           1       0.89      0.83      0.86       306
           2       0.98      0.97      0.98       405
           3       0.95      0.96      0.96       300

    accuracy                           0.92      1311
   macro avg       0.91      0.91      0.91      1311
weighted avg       0.92      0.92      0.92      1311

